# Generated by Django 4.0.3 on 2022-05-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('pudate', models.DateTimeField()),
                ('pic', models.ImageField(upload_to='news/%y/%m')),
            ],
        ),
    ]
