# Generated by Django 4.0.3 on 2022-08-22 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_topic_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='pic',
            new_name='image',
        ),
    ]
