# Generated by Django 4.0.3 on 2022-05-30 13:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('제목', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('pudate', models.DateTimeField(default=datetime.datetime(2022, 5, 30, 13, 12, 43, 770789, tzinfo=utc))),
                ('글쓴이', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='글쓴이', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
