# Generated by Django 4.0.3 on 2022-07-19 06:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0034_alter_radio_pudate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radio',
            name='pudate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 6, 34, 34, 231222, tzinfo=utc)),
        ),
    ]
