# Generated by Django 4.0.3 on 2022-08-12 02:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0041_alter_radio_pudate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radio',
            name='pudate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 2, 24, 3, 593847, tzinfo=utc)),
        ),
    ]
