# Generated by Django 4.0.3 on 2022-07-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_club_content_alter_club_pudate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='user',
        ),
        migrations.AlterField(
            model_name='detail',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
