# Generated by Django 4.0.3 on 2022-07-11 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_remove_detail_user_alter_detail_content'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='index',
            table='First',
        ),
    ]
