# Generated by Django 4.0.3 on 2022-07-18 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_index_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='index',
            table=None,
        ),
    ]
