# Generated by Django 4.0.3 on 2022-07-18 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_index_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='index',
            new_name='First'
        )
    ]
