# Generated by Django 4.0.3 on 2022-07-19 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_auto_20220718_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='first',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.first'),
        ),
    ]
