# Generated by Django 4.0.3 on 2022-07-19 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_detail_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='first',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.first'),
        ),
    ]
