# Generated by Django 4.0.3 on 2022-07-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
