# Generated by Django 4.0.3 on 2022-07-28 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soccer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('pic', models.ImageField(upload_to='soccer/%y/%m')),
            ],
        ),
        migrations.CreateModel(
            name='Diarys',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=200)),
                ('pudate', models.DateTimeField()),
                ('soccer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.soccer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diarys_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiaryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='media/diarys/default_image.jpeg', null=True, upload_to='diarys')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.diarys')),
            ],
        ),
    ]
